//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho.WebView.Painel {
    
    
    public partial class Financeiro {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Trabalho.WebView.Layout.Layout Master {
            get {
                return ((Trabalho.WebView.Layout.Layout)(base.Master));
            }
        }
    }
}
